### ISSUE TITLE
Trimming multiple trailing .md extensions leeds to permanent redirect

### ISSUE THREAD

**Issue by delimitry** [life4/chameleon#2]
Trimming multiple trailing .md extensions leeds to permanent redirect.

Examples:
1) `https://articles.life4web.ru/eng/.md.md.md` -> `https://articles.life4web.ru/eng/` - OK (but maybe it should be 404)
2) `https://articles.life4web.ru/eng/python-round.md.md.md.md.md.md.md.md.md.md.md.md` -> `https://articles.life4web.ru/eng/python-round/` - OK (but maybe it should be 404)
3) `https://articles.life4web.ru/eng/.md.md.md.md.md.md.md.md.md.md.md.md.md.md.md.md.md.md.md` -> Permanent Redirect

**Comment by orsinium** [comment]
Fixed in #4, thank you :)
